# Generated by Django 4.2.19 on 2025-02-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-user.png', null=True, upload_to='profile_pics'),
        ),
    ]
