# Generated by Django 4.2.19 on 2025-02-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailingredient',
            name='amount',
            field=models.CharField(default='To taste', max_length=100),
        ),
    ]
